### ISSUE TITLE
Cache-Control header should not be mandatory

### ISSUE THREAD

**Issue by jmbourdaret** [camptocamp/c2cwsgiutils#1160]
I'm not sure about this but the web service should be able to answer *without* having a `Cache-Control` header.
(unless it breaks some best practices that I'm not aware of)

https://github.com/camptocamp/c2cwsgiutils/blob/6403bd3e3e06e188c0f56d89ec04500b8a3b7450/c2cwsgiutils/acceptance/connection.py#L231-L237

here, assertions fails if the header is absent. it doesn't matter wether or not `CacheExpected.YES/NO` is set,
```assert "Cache-Control" in r.headers```
will generate a failure either way

(For my use case, GeoServer does not include the `Cache-Control` header in its answer to WFS GetCap. caching can be handled differently)

**Comment by sbrunner** [comment]
The code you point is to test that the cache control is what we expected in the c2cwsgiutils responses, for me, this function shouldn't be use on an external service...
You probably should create your own function to check the status code.

**Comment by jmbourdaret** [comment]
Thanks,
I use the `get_xml()` function to get the WFS, like it is done for mapserver CI here :
https://github.com/camptocamp/docker-mapserver/blob/master/acceptance_tests/test_wfs.py

But I just noticed that I could use `CacheExpected.DONT_CARE` in get_xml. it is defaulted to NO:
https://github.com/camptocamp/c2cwsgiutils/blob/6403bd3e3e06e188c0f56d89ec04500b8a3b7450/c2cwsgiutils/acceptance/connection.py#L81

It seems to work now.

**Comment by sbrunner** [comment]
My dream it to get out c2cwsgiutils test from this kind of project...

Personally, I don't recommend to use c2cgiutils tests, the only benefit it to be able to do some test on service reconnection, for other cases it's too complicated for a small benefit...

CU
Stéph

**Comment by jmbourdaret** [comment]
Ok , thanks . 
I'll see if I can get this out of my project CI.
For now, it works with `get_xml( ..., cache_expected=CacheExpected.DONT_CARE, cors=False)`

I'll close the issue, it was more or less due to my misunderstanding of c2cwsgiutils

Have a nice holidays

**Comment by sbrunner** [comment]
Thanks, you too :-)
