### ISSUE TITLE
sqlalchemylogger (SQLAlchemyHandler) supported with gunicorn?

### ISSUE THREAD

**Issue by peterschaer** [camptocamp/c2cwsgiutils#1272]
I'm using the sqlalchemylogger (SQLAlchemyHandler) in our [pyramid_oereb](https://github.com/openoereb/pyramid_oereb)-Application. It is used in the builtin stats functionality (https://openoereb.github.io/pyramid_oereb/contrib/stats.html). Now we have a configuration that's running very well with waitress as a WSGI Server. For a new release we'd like to switch from waitress to gunicorn. But we do not manage to get the sqlalchemylogger to work with gunicorn. The application itself does work but it does not log to the configured database. Is the sqlalchemylogger supported on gunicorn at all?

**Comment by jwkaltz** [comment]
Hi Peter, we tested the statistics functionality in pyramid_oereb V2 here:
https://github.com/openoereb/pyramid_oereb/pull/1480
But indeed, within the pyramid_oereb development environment, gunicorn is not used. 
I do have gunicorn running in two pyramid_oereb projects, but these in turn do not use the statistics functionality.
To my knowledge, cantons Aargau and Ticino are using it in V1, but Aargau is not using gunicorn, and I don't know about Ticino.
Thus, I don't know if the functionality has ever been used in gunicorn.
If you like, you can paste here what you have tried so far, and we can have a look via maintenance budget how to make it work with gunicorn?

**Comment by mki-c2c** [comment]
hello @peterschaer 
I habe confirmed the issue also with a standard dev installation, gunicorn logs do not use the handlers defined by default in development.ini.
I am testing with logger setup in config.py as mentioned here: https://github.com/camptocamp/c2cwsgiutils/blob/master/acceptance_tests/app/gunicorn.conf.py
I already manage to register the handlers, and I'll keep you informed when I manage to set up logging.

**Comment by mki-c2c** [comment]
hello @peterschaer 
I have figured out a solution for your config:
As you mentioned, I also had some difficulty with the forking mechanism.

A solution is to force logger configuration in a post-fork step with the option `'extend_existing': True`

you have two options to customize the file `gunicorn_config.py`:

### setup from `.ini` config file:
```
from logging.config import fileConfig

def post_fork(server, worker):
    fileConfig("production.ini")
```
Please take care to set the flag `'extend_existing': True` in `production.ini` (or `production.mako`) as shown in the example below
```
[handler_sqlalchemylogger]
class = c2cwsgiutils.sqlalchemylogger.handlers.SQLAlchemyHandler
args = ({'url':'postgresql://bla','tablename':'bla','tableargs': {'schema':'bla', 'extend_existing': 'True'}},'healthcheck')
```


### setup as an inline dict in `gunicorn_config.py`:
```
from logging.config import dictConfig

def post_fork(server, worker):
    dictConfig(
        {
            "version": 1,
            "incremental": False,
            "root": {
                "level": "INFO",
                "handlers": ["console"],
            },
            "loggers": {
                "gunicorn.error": {"level": "INFO", "handlers": ["console"]},
                "gunicorn.access": {"level": "INFO", "handlers": ["console"]},
                "JSON": {"level": "INFO", "qualname": "JSON",  "handlers": ["sqlalchemylogger"]},
                "sqlalchemy": {"level": "DEBUG", "qualname": "sqlalchemy.engine"},
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "formatter": "generic",
                    "stream": "ext://sys.stdout",
                },
                "sqlalchemylogger": {
                    "class": "c2cwsgiutils.sqlalchemylogger.handlers.SQLAlchemyHandler",
                    "sqlalchemy_url": {
                        'url': 'postgresql://postgres:postgres@oereb-db:5432/oereb_stats',
                        'tablename': 'logs',
                        'tableargs': {'schema': 'oereb_logs', 'extend_existing': True}
                    },
                    "level": "INFO"
                },
            },
            "formatters": {
                "generic": {
                    "format": "%(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s",
                }
            },
        }
    )
```
Let me know if one of these solutions works for you or if you continue having problems.

**Comment by peterschaer** [comment]
Hi @mki-c2c 
Thanks for your research. I tried "setup from .ini config file" and that works very well in my setup. The logger is now working with gunicorn. Thank you very much!
