### ISSUE TITLE
Dependencies versions should not been fixed in such project

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/c2cwsgiutils#2]
We were thinking to use this some helpers (for example helpers for cors headers in HTTPError reponse) from c2cwsgiutils in c2corg/v6_api.
And it may a problem for us that this project depends on precise versions of dependencies.

**Comment by arnaud-morvan** [comment]
@pvalsecc : what do you think about this ?

**Comment by arnaud-morvan** [comment]
After some tests, our setup take the version from our requirements file, not the one from c2cwsgiutils ``install_requires`` , without any error.
But I do not understand why I do not get error ?

**Comment by pvalsecc** [comment]
To me, versions should be fixed. Otherwise, they are never updated in a Docker environment. If nothing changes, docker build doesn't even try to run a the pip install command.
If you specify a newer version in your requirement.txt file. It will take it.
