### ISSUE TITLE
Multistage build is unusable

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/c2cwsgiutils#574]
A bunch of Debian packages are downloaded each time a change occurs in the code.
Unless with super fast network it makes working with c2cwsgiutils very painful and time consuming.

This is due to "make run" depending on the full build, which depends on the lite build, which depends on all the code. See https://github.com/camptocamp/c2cwsgiutils/blob/master/Dockerfile

I had a quick stab to it, but a fix will be a bit invasive and I would like to know if you have any thought about this problem.

**Comment by sbrunner** [comment]
Is it steel the case?

**Comment by gberaudo** [comment]
Indeed, we fixed it. I will close the issue.
