### ISSUE TITLE
Regular rebuild of the images

### ISSUE THREAD

**Issue by gberaudo** [camptocamp/c2cwsgiutils#7]
As discussed, to ensure images based on c2cwsgiutils get up-to-date versions of Debian, we need to:
- have a branch rebuilt regularily (branch 0);
- this branch should contain the latest released version;
- a cron would pull up-to-date Docker dependencies and rebuild and push updated image to Docker hub.

**Comment by pvalsecc** [comment]
OK, this is now in place. If you reference camptocamp/c2cwsgiutils:0, you'll get that.
