### ISSUE TITLE
Redis health check are not activated

### ISSUE THREAD

**Issue by fredj** [camptocamp/c2cwsgiutils#837]
Redis health check must be added by default but it's not the case when `C2C_REDIS_SENTINELS` is not set.

See https://github.com/camptocamp/c2cwsgiutils/blob/release_4/c2cwsgiutils/health_check.py#L101:
Because `C2C_REDIS_SENTINELS`is set to an empty string in Dockerfile:
https://github.com/camptocamp/c2cwsgiutils/blob/release_4/Dockerfile#L65
the value of `C2C_REDIS_URL` is not evaluated

**Comment by fredj** [comment]
Probably the same issue for all the optional variables set to empty string

**Comment by gberaudo** [comment]
@sbrunner, should this issue be closed?

**Comment by sbrunner** [comment]
For me yes :-)
